use_frameworks!

platform :ios, '10.0'

target 'YDEmptyView_Example' do
  pod 'YDEmptyView', :path => '../'

  target 'YDEmptyView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
